# Generated by Django 3.2.9 on 2021-11-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Latname',
            new_name='Lastname',
        ),
    ]
